### ISSUE TITLE
Confusing requirements

### ISSUE THREAD

**Issue by yankouskia** [deser/eslint-plugin-import-force-abbr#7]
In regards to docs of [abbr plugin](https://github.com/deser/eslint-plugin-import-force-abbr/blob/master/docs/rules/abbr.md), what's correct usage for this case?
```js
import * as AppHelpers from 'AppHelpers';
import * as ArrayHelpers from 'ArrayHelpers';
import * as AdapterHelpers from '../AdapterHelpers';
```

**Comment by deser** [comment]
Naming conventions are voluntary.
apph
arrh
adh
